-- Create new table
CREATE TABLE properties_2016_df1 (
	parcelid INT NOT NULL,
	bathroomcnt FLOAT(53) NOT NULL,
	bedroomcnt FLOAT(53) NOT NULL,
	buildingqualitytypeid FLOAT(53) NOT NULL,
	calculatedbathnbr FLOAT(53) NOT NULL,
	calculatedfinishedsquarefeet FLOAT(53) NOT NULL,
	fips FLOAT(53) NOT NULL,
	fullbatchcnt FLOAT(53) NOT NULL,
	latitude FLOAT(53) NOT NULL,
	longitude FLOAT(53) NOT NULL,
	lotsizesquarefeet FLOAT(53) NOT NULL,
	propertycountylandusecode VARCHAR(64) NOT NULL,
	propertylandusetypeid FLOAT(53) NOT NULL,
	rawcensustractandblock FLOAT(53) NOT NULL,
	regionidcity FLOAT(53) NOT NULL,
	regionidzip FLOAT(53) NOT NULL,
	roomcnt FLOAT(53) NOT NULL,
	yearbuilt FLOAT(53) NOT NULL,
	structuretaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxvaluedollarcnt FLOAT(53) NOT NULL,
	assessmentyear FLOAT(53) NOT NULL,
	landtaxvaluedollarcnt FLOAT(53) NOT NULL,
	censustractandblovk FLOAT(53) NOT NULL,
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
	);
	
	
CREATE TABLE properties_2016_df2 (
	parcelid INT NOT NULL,
	bathroomcnt FLOAT(53) NOT NULL,
	bedroomcnt FLOAT(53) NOT NULL,
	buildingqualitytypeid FLOAT(53) NOT NULL,
	calculatedbathnbr FLOAT(53) NOT NULL,
	calculatedfinishedsquarefeet FLOAT(53) NOT NULL,
	fips FLOAT(53) NOT NULL,
	fullbatchcnt FLOAT(53) NOT NULL,
	latitude FLOAT(53) NOT NULL,
	longitude FLOAT(53) NOT NULL,
	lotsizesquarefeet FLOAT(53) NOT NULL,
	propertycountylandusecode VARCHAR(64) NOT NULL,
	propertylandusetypeid FLOAT(53) NOT NULL,
	rawcensustractandblock FLOAT(53) NOT NULL,
	regionidcity FLOAT(53) NOT NULL,
	regionidcounty FLOAT(53) NOT NULL,
	regionidzip FLOAT(53) NOT NULL,
	roomcnt FLOAT(53) NOT NULL,
	yearbuilt FLOAT(53) NOT NULL,
	structuretaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxvaluedollarcnt FLOAT(53) NOT NULL,
	assessmentyear FLOAT(53) NOT NULL,
	landtaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxamount FLOAT(53) NOT NULL,
	censustractandblovk FLOAT(53) NOT NULL,
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);

CREATE TABLE properties_2016_df3 (
	parcelid INT NOT NULL,
	bathroomcnt FLOAT(53) NOT NULL,
	bedroomcnt FLOAT(53) NOT NULL,
	buildingqualitytypeid FLOAT(53) NOT NULL,
	calculatedbathnbr FLOAT(53) NOT NULL,
	calculatedfinishedsquarefeet FLOAT(53) NOT NULL,
	fips FLOAT(53) NOT NULL,
	fullbatchcnt FLOAT(53) NOT NULL,
	latitude FLOAT(53) NOT NULL,
	longitude FLOAT(53) NOT NULL,
	lotsizesquarefeet FLOAT(53) NOT NULL,
	propertycountylandusecode VARCHAR(64) NOT NULL,
	propertylandusetypeid FLOAT(53) NOT NULL,
	rawcensustractandblock FLOAT(53) NOT NULL,
	regionidcity FLOAT(53) NOT NULL,
	regionidzip FLOAT(53) NOT NULL,
	roomcnt FLOAT(53) NOT NULL,
	yearbuilt FLOAT(53) NOT NULL,
	structuretaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxvaluedollarcnt FLOAT(53) NOT NULL,
	assessmentyear FLOAT(53) NOT NULL,
	landtaxvaluedollarcnt FLOAT(53) NOT NULL,
	censustractandblovk FLOAT(53) NOT NULL,
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
	);
	
	
CREATE TABLE properties_2016_df4 (
	parcelid INT NOT NULL,
	bathroomcnt FLOAT(53) NOT NULL,
	bedroomcnt FLOAT(53) NOT NULL,
	buildingqualitytypeid FLOAT(53) NOT NULL,
	calculatedbathnbr FLOAT(53) NOT NULL,
	calculatedfinishedsquarefeet FLOAT(53) NOT NULL,
	fips FLOAT(53) NOT NULL,
	fullbatchcnt FLOAT(53) NOT NULL,
	latitude FLOAT(53) NOT NULL,
	longitude FLOAT(53) NOT NULL,
	lotsizesquarefeet FLOAT(53) NOT NULL,
	propertycountylandusecode VARCHAR(64) NOT NULL,
	propertylandusetypeid FLOAT(53) NOT NULL,
	rawcensustractandblock FLOAT(53) NOT NULL,
	regionidcity FLOAT(53) NOT NULL,
	regionidcounty FLOAT(53) NOT NULL,
	regionidzip FLOAT(53) NOT NULL,
	roomcnt FLOAT(53) NOT NULL,
	yearbuilt FLOAT(53) NOT NULL,
	structuretaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxvaluedollarcnt FLOAT(53) NOT NULL,
	assessmentyear FLOAT(53) NOT NULL,
	landtaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxamount FLOAT(53) NOT NULL,
	censustractandblovk FLOAT(53) NOT NULL,
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);

CREATE TABLE properties_2016_df5 (
	parcelid INT NOT NULL,
	bathroomcnt FLOAT(53) NOT NULL,
	bedroomcnt FLOAT(53) NOT NULL,
	buildingqualitytypeid FLOAT(53) NOT NULL,
	calculatedbathnbr FLOAT(53) NOT NULL,
	calculatedfinishedsquarefeet FLOAT(53) NOT NULL,
	fips FLOAT(53) NOT NULL,
	fullbatchcnt FLOAT(53) NOT NULL,
	latitude FLOAT(53) NOT NULL,
	longitude FLOAT(53) NOT NULL,
	lotsizesquarefeet FLOAT(53) NOT NULL,
	propertycountylandusecode VARCHAR(64) NOT NULL,
	propertylandusetypeid FLOAT(53) NOT NULL,
	rawcensustractandblock FLOAT(53) NOT NULL,
	regionidcity FLOAT(53) NOT NULL,
	regionidzip FLOAT(53) NOT NULL,
	roomcnt FLOAT(53) NOT NULL,
	yearbuilt FLOAT(53) NOT NULL,
	structuretaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxvaluedollarcnt FLOAT(53) NOT NULL,
	assessmentyear FLOAT(53) NOT NULL,
	landtaxvaluedollarcnt FLOAT(53) NOT NULL,
	censustractandblovk FLOAT(53) NOT NULL,
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
	);
	
	
CREATE TABLE properties_2016_df6 (
	parcelid INT NOT NULL,
	bathroomcnt FLOAT(53) NOT NULL,
	bedroomcnt FLOAT(53) NOT NULL,
	buildingqualitytypeid FLOAT(53) NOT NULL,
	calculatedbathnbr FLOAT(53) NOT NULL,
	calculatedfinishedsquarefeet FLOAT(53) NOT NULL,
	fips FLOAT(53) NOT NULL,
	fullbatchcnt FLOAT(53) NOT NULL,
	latitude FLOAT(53) NOT NULL,
	longitude FLOAT(53) NOT NULL,
	lotsizesquarefeet FLOAT(53) NOT NULL,
	propertycountylandusecode VARCHAR(64) NOT NULL,
	propertylandusetypeid FLOAT(53) NOT NULL,
	rawcensustractandblock FLOAT(53) NOT NULL,
	regionidcity FLOAT(53) NOT NULL,
	regionidcounty FLOAT(53) NOT NULL,
	regionidzip FLOAT(53) NOT NULL,
	roomcnt FLOAT(53) NOT NULL,
	yearbuilt FLOAT(53) NOT NULL,
	structuretaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxvaluedollarcnt FLOAT(53) NOT NULL,
	assessmentyear FLOAT(53) NOT NULL,
	landtaxvaluedollarcnt FLOAT(53) NOT NULL,
	taxamount FLOAT(53) NOT NULL,
	censustractandblovk FLOAT(53) NOT NULL,
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);

CREATE TABLE properties_2017_df1 (
	parcelid INT,
	bathroomcnt FLOAT(53),
	bedroomcnt FLOAT(53),
	buildingqualitytypeid FLOAT(53),
	calculatedbathnbr FLOAT(53),
	calculatedfinishedsquarefeet FLOAT(53),
	fips FLOAT(53),
	fullbatchcnt FLOAT(53),
	latitude FLOAT(53),
	longitude FLOAT(53),
	lotsizesquarefeet FLOAT(53),
	propertycountylandusecode VARCHAR(64),
	propertylandusetypeid FLOAT(53),
	rawcensustractandblock FLOAT(53),
	regionidcity FLOAT(53),
	regionidcounty FLOAT(53),
	regionidzip FLOAT(53),
	roomcnt FLOAT(53),
	yearbuilt FLOAT(53),
	structuretaxvaluedollarcnt FLOAT(53),
	taxvaluedollarcnt FLOAT(53),
	assessmentyear FLOAT(53),
	landtaxvaluedollarcnt FLOAT(53),
	taxamount FLOAT(53),
	censustractandblovk FLOAT(53),
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);

CREATE TABLE properties_2017_df2 (
	parcelid INT,
	bathroomcnt FLOAT(53),
	bedroomcnt FLOAT(53),
	buildingqualitytypeid FLOAT(53),
	calculatedbathnbr FLOAT(53),
	calculatedfinishedsquarefeet FLOAT(53),
	fips FLOAT(53),
	fullbatchcnt FLOAT(53),
	latitude FLOAT(53),
	longitude FLOAT(53),
	lotsizesquarefeet FLOAT(53),
	propertycountylandusecode VARCHAR(64),
	propertylandusetypeid FLOAT(53),
	rawcensustractandblock FLOAT(53),
	regionidcity FLOAT(53),
	regionidcounty FLOAT(53),
	regionidzip FLOAT(53),
	roomcnt FLOAT(53),
	yearbuilt FLOAT(53),
	structuretaxvaluedollarcnt FLOAT(53),
	taxvaluedollarcnt FLOAT(53),
	assessmentyear FLOAT(53),
	landtaxvaluedollarcnt FLOAT(53),
	taxamount FLOAT(53),
	censustractandblovk FLOAT(53),
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);

CREATE TABLE properties_2017_df3 (
	parcelid INT,
	bathroomcnt FLOAT(53),
	bedroomcnt FLOAT(53),
	buildingqualitytypeid FLOAT(53),
	calculatedbathnbr FLOAT(53),
	calculatedfinishedsquarefeet FLOAT(53),
	fips FLOAT(53),
	fullbatchcnt FLOAT(53),
	latitude FLOAT(53),
	longitude FLOAT(53),
	lotsizesquarefeet FLOAT(53),
	propertycountylandusecode VARCHAR(64),
	propertylandusetypeid FLOAT(53),
	rawcensustractandblock FLOAT(53),
	regionidcity FLOAT(53),
	regionidcounty FLOAT(53),
	regionidzip FLOAT(53),
	roomcnt FLOAT(53),
	yearbuilt FLOAT(53),
	structuretaxvaluedollarcnt FLOAT(53),
	taxvaluedollarcnt FLOAT(53),
	assessmentyear FLOAT(53),
	landtaxvaluedollarcnt FLOAT(53),
	taxamount FLOAT(53),
	censustractandblovk FLOAT(53),
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);

CREATE TABLE properties_2017_df4 (
	parcelid INT,
	bathroomcnt FLOAT(53),
	bedroomcnt FLOAT(53),
	buildingqualitytypeid FLOAT(53),
	calculatedbathnbr FLOAT(53),
	calculatedfinishedsquarefeet FLOAT(53),
	fips FLOAT(53),
	fullbatchcnt FLOAT(53),
	latitude FLOAT(53),
	longitude FLOAT(53),
	lotsizesquarefeet FLOAT(53),
	propertycountylandusecode VARCHAR(64),
	propertylandusetypeid FLOAT(53),
	rawcensustractandblock FLOAT(53),
	regionidcity FLOAT(53),
	regionidcounty FLOAT(53),
	regionidzip FLOAT(53),
	roomcnt FLOAT(53),
	yearbuilt FLOAT(53),
	structuretaxvaluedollarcnt FLOAT(53),
	taxvaluedollarcnt FLOAT(53),
	assessmentyear FLOAT(53),
	landtaxvaluedollarcnt FLOAT(53),
	taxamount FLOAT(53),
	censustractandblovk FLOAT(53),
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);

CREATE TABLE properties_2017_df5 (
	parcelid INT,
	bathroomcnt FLOAT(53),
	bedroomcnt FLOAT(53),
	buildingqualitytypeid FLOAT(53),
	calculatedbathnbr FLOAT(53),
	calculatedfinishedsquarefeet FLOAT(53),
	fips FLOAT(53),
	fullbatchcnt FLOAT(53),
	latitude FLOAT(53),
	longitude FLOAT(53),
	lotsizesquarefeet FLOAT(53),
	propertycountylandusecode VARCHAR(64),
	propertylandusetypeid FLOAT(53),
	rawcensustractandblock FLOAT(53),
	regionidcity FLOAT(53),
	regionidcounty FLOAT(53),
	regionidzip FLOAT(53),
	roomcnt FLOAT(53),
	yearbuilt FLOAT(53),
	structuretaxvaluedollarcnt FLOAT(53),
	taxvaluedollarcnt FLOAT(53),
	assessmentyear FLOAT(53),
	landtaxvaluedollarcnt FLOAT(53),
	taxamount FLOAT(53),
	censustractandblovk FLOAT(53),
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);
CREATE TABLE properties_2017_df6 (
	parcelid INT,
	bathroomcnt FLOAT(53),
	bedroomcnt FLOAT(53),
	buildingqualitytypeid FLOAT(53),
	calculatedbathnbr FLOAT(53),
	calculatedfinishedsquarefeet FLOAT(53),
	fips FLOAT(53),
	fullbatchcnt FLOAT(53),
	latitude FLOAT(53),
	longitude FLOAT(53),
	lotsizesquarefeet FLOAT(53),
	propertycountylandusecode VARCHAR(64),
	propertylandusetypeid FLOAT(53),
	rawcensustractandblock FLOAT(53),
	regionidcity FLOAT(53),
	regionidcounty FLOAT(53),
	regionidzip FLOAT(53),
	roomcnt FLOAT(53),
	yearbuilt FLOAT(53),
	structuretaxvaluedollarcnt FLOAT(53),
	taxvaluedollarcnt FLOAT(53),
	assessmentyear FLOAT(53),
	landtaxvaluedollarcnt FLOAT(53),
	taxamount FLOAT(53),
	censustractandblovk FLOAT(53),
	PRIMARY KEY (parcelid),
	UNIQUE (parcelid)
);