CREATE TABLE zillow_durham_county (
	date_sold VARCHAR(64),
	property_type VARCHAR(64),
	lot_area_value FLOAT(53),
	address VARCHAR(64),
	variable_data VARCHAR(64),
	variale_data_2 VARCHAR(64),
	zestimate FLOAT(53),
	img_src VARCHAR(15000),
	price INT,
	bedrooms INT,
	contingent_listing_type VARCHAR(64),
	longitude FLOAT(53),
	latitude FLOAT(53),
	listing_status VARCHAR(64),
	zpid INT,
	rent_zestimate INT,
	days_on_zillow INT,
	bathrooms FLOAT(53),
	living_area FLOAT(53),
	country VARCHAR(64),
	currency VARCHAR(64),
	lot_area_unit VARCHAR(64),
	has_image VARCHAR(64)
);

CREATE TABLE zillow_wake_county (
	date_sold VARCHAR(64),
	property_type VARCHAR(64),
	lot_area_value FLOAT(53),
	address VARCHAR(1500),
	variable_data VARCHAR(64),
	variale_data_2 VARCHAR(64),
	zestimate FLOAT(53),
	img_src VARCHAR(1500),
	price INT,
	bedrooms VARCHAR(64),
	contingent_listing_type VARCHAR(64),
	longitude FLOAT(53),
	latitude FLOAT(53),
	listing_status VARCHAR(64),
	zpid INT,
	rent_zestimate INT,
	days_on_zillow INT,
	bathrooms FLOAT(53),
	living_area FLOAT(53),
	country VARCHAR(64),
	currency VARCHAR(64),
	lot_area_unit VARCHAR(64),
	has_image VARCHAR(64)
);